--------------------------------------------------------
--  File created - Thursday-October-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QTMS_CODE_VALUES
--------------------------------------------------------

  CREATE TABLE "QTMS_CODE_VALUES" ("ID" NUMBER, "CODE_DESC" VARCHAR2(40), "CODE_VALUE" VARCHAR2(40)) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
REM INSERTING into QTMS_CODE_VALUES
SET DEFINE OFF;
Insert into QTMS_CODE_VALUES (ID,CODE_DESC,CODE_VALUE) values (1,'student_reg_status','Need to Attend Next Demo');
Insert into QTMS_CODE_VALUES (ID,CODE_DESC,CODE_VALUE) values (2,'student_reg_status','Need to Followup');
Insert into QTMS_CODE_VALUES (ID,CODE_DESC,CODE_VALUE) values (3,'student_reg_status','NotIntrested');
Insert into QTMS_CODE_VALUES (ID,CODE_DESC,CODE_VALUE) values (4,'student_reg_status','Confirmed');

--------------------------------------------------------
--  File created - Thursday-October-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QTMS_COURSE
--------------------------------------------------------

  CREATE TABLE "QTMS_COURSE" ("ID" NUMBER, "NAME" VARCHAR2(20), "FEE" NUMBER, "DURATION" NUMBER) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
REM INSERTING into QTMS_COURSE
SET DEFINE OFF;
Insert into QTMS_COURSE (ID,NAME,FEE,DURATION) values (1,'java',5000,30);
Insert into QTMS_COURSE (ID,NAME,FEE,DURATION) values (2,'python',5000,30);
Insert into QTMS_COURSE (ID,NAME,FEE,DURATION) values (3,'DataScience',25000,45);
Insert into QTMS_COURSE (ID,NAME,FEE,DURATION) values (4,'AutomationTesting',10000,45);
--------------------------------------------------------
--  DDL for Index SYS_C008827
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008827" ON "QTMS_COURSE" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--------------------------------------------------------
--  Constraints for Table QTMS_COURSE
--------------------------------------------------------

  ALTER TABLE "QTMS_COURSE" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE

--------------------------------------------------------
--  File created - Thursday-October-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QTSM_STUDENT
--------------------------------------------------------

  CREATE TABLE "QTSM_STUDENT" ("ID" NUMBER, "NAME" VARCHAR2(20), "MOBILE" NUMBER, "EMAIL" VARCHAR2(20), "COURSE" VARCHAR2(10), "STATUS" VARCHAR2(20), "FIRST_REMAINDER_MAIL_SENT" CHAR(1), "FIRST_REMAINDER_SMS_SENT" CHAR(1), "ENQUIRED_ON" DATE) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
REM INSERTING into QTSM_STUDENT
SET DEFINE OFF;
Insert into QTSM_STUDENT (ID,NAME,MOBILE,EMAIL,COURSE,STATUS,FIRST_REMAINDER_MAIL_SENT,FIRST_REMAINDER_SMS_SENT,ENQUIRED_ON) values (1,'kiran',87695468,'kiran@gmail.com','java','Need to attend demo','N','N',to_date('16-OCT-22','DD-MON-RR'));
Insert into QTSM_STUDENT (ID,NAME,MOBILE,EMAIL,COURSE,STATUS,FIRST_REMAINDER_MAIL_SENT,FIRST_REMAINDER_SMS_SENT,ENQUIRED_ON) values (2,'jeevan',1216767,'jeevann@gmail.com','python','Need to followuup','N','N',to_date('15-OCT-22','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SYS_C008804
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C008804" ON "QTSM_STUDENT" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--------------------------------------------------------
--  Constraints for Table QTSM_STUDENT
--------------------------------------------------------

  ALTER TABLE "QTSM_STUDENT" ADD PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE

CREATE TABLE "QTMS_FACULTY" ("ID" NUMBER NOT NULL, "NAME" VARCHAR2(20), "COURSE_TEACHING" VARCHAR2(25), "EMAIL" VARCHAR2(25), "MOBILE" NUMBER(10), "QUALIFICATION" VARCHAR2(20), "INTERVIEWED_ON" NUMBER(10), "LOCATION" VARCHAR2(30), "TRAINING_MODE" VARCHAR2(10), FEEDBACK VARCHAR2(50),INTERVIEWER_NAME VARCHAR2(20),INTERVIEWER_CONTACT NUMBER(10), REMARKS VARCHAR2(35),TEACHING_EXPERIENCE VARCHAR(35)); 
CREATE TABLE "QTMS_PATIENT" ("ID" NUMBER(3) NOT NULL, "GENDER" VARCHAR2(20), "AGE" VARCHAR2(25), "MARTIAL_STATUS" VARCHAR2(25), "FULNAME" VARCHAR2(20), "CITY" VARCHAR2(20), "DISTRICT" VARCHAR2(20), "STATE" VARCHAR2(20), "ZIPCODE" VARCHAR2(20), TEMPERATURE VARCHAR2(20),BLOOD_PRESSURE VARCHAR2(20),HEIGHT VARCHAR2(20), WEIGHT VARCHAR2(20),CONSULT_DOCTOR VARCHAR2(20),HABITS VARCHAR2(40),TYPES_PATIENT VARCHAR2(20)); 
